apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devopsdays-ecommerce
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/name: devopsdays-ecommerce
    app.kubernetes.io/part-of: devopsdays-ecommerce
spec:
  project: default
  source:
    repoURL: https://github.com/orpheezt/devopsdays-ebpf-nocode-o11y.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: devopsdays
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
