apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-py
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: gateway-py
    app.kubernetes.io/instance: gateway-py
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: devopsdays-ecommerce
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-py
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway-py
        app.kubernetes.io/instance: gateway-py
        app.kubernetes.io/component: api-gateway
        app.kubernetes.io/part-of: devopsdays-ecommerce
        app: gateway-py
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: gateway-py
          image: localhost/api-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: ORDER_PAYMENT_URL
              value: "http://payment-go:8081"
            - name: ORDER_INVENTORY_URL
              value: "http://inventory-rs:8082"
          startupProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sleep", "5"]
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-py
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app.kubernetes.io/name: gateway-py
    app.kubernetes.io/instance: gateway-py
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: devopsdays-ecommerce
    app.kubernetes.io/managed-by: kustomize
    app: gateway-py
spec:
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  selector:
    app.kubernetes.io/name: gateway-py
