apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: devopsdays

resources:
  - postgres.yaml
  - valkey.yaml
  - shipping-quarkus.yaml
  - antifraud-fastify.yaml
  - payment-go.yaml
  - inventory-rs.yaml
  - gateway-py.yaml
