apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: devopsdays
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: docker.io/valkey/valkey:9.1.1-trixie
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: valkey
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: devopsdays
  labels:
    app: valkey
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: valkey
  selector:
    app: valkey
