quarkus.http.port=8084

# SmallRye Health mapping strictly to /livez and /readyz
quarkus.smallrye-health.root-path=/
quarkus.smallrye-health.liveness-path=livez
quarkus.smallrye-health.readiness-path=readyz
